### ISSUE TITLE
Change of start time/ end time to start date/end date 

### ISSUE THREAD

**Issue by ellesmith88** [roocs/roocs-utils#3]
### Description

Clisops core subset expects `start_date` and `end_date` in a dictionary. We had been using `start_time` and `end_time` to be consistent with the name `TimeParameter`. Should this stay as it is?

**Comment by agstephens** [comment]
@ellesmith88 , I think we should preserve `clisops.core.subset` so that it preserves the existing interface, as used by `xclim`. 
So our input parameter checks only need to go as far as `clisops.ops.subset` - and inside that function we can translate the parameters into the form required by the `clisops.core.subset.*` functions.
